# Generated by Django 4.2.18 on 2025-02-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGameCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_game_date', models.DateField(auto_now_add=True)),
                ('game_counter', models.PositiveIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('account', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prepaid', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_earning', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_earning', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('min_stake', models.DecimalField(decimal_places=0, max_digits=10)),
                ('cut_percentage', models.DecimalField(decimal_places=2, default=0.2, max_digits=5)),
                ('cut_bouldery', models.IntegerField(default=100)),
                ('backup_password', models.CharField(default='', max_length=255)),
                ('agent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='agent.agent')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
