# Generated by Django 4.2.3 on 2024-05-22 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_backup_password'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='backup_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='agent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to='agent.agent'),
        ),
    ]
