# Generated by Django 4.2.3 on 2025-10-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_agent_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='jackpot_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Jackpot threshold amount (in birr) to trigger payout', max_digits=15),
        ),
        migrations.AddField(
            model_name='account',
            name='jackpot_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current accumulated jackpot pool', max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='jackpot_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of each prize to contribute to jackpot (e.g., 2.00 for 2%)', max_digits=5),
        ),
    ]
