# Generated by Django 4.2.3 on 2024-07-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_cut_bouldery_account_cut_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='prepaid',
            field=models.BooleanField(default=True),
        ),
    ]
