# Generated by Django 4.2.3 on 2025-10-16 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_account_jackpot_amount_account_jackpot_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_info', models.BooleanField(default=True)),
                ('cartela', models.CharField(choices=[('super', 'Super'), ('dallol', 'Dallol'), ('africa', 'Africa'), ('hummer', 'Hummer')], default='dallol', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
