# Generated by Django 4.2.3 on 2025-10-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patterns',
            field=models.JSONField(default=list),
        ),
    ]
