# Generated by Django 4.2.3 on 2025-10-16 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_profile_patterns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cartela',
        ),
    ]
