# Generated by Django 4.2.3 on 2025-10-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_cartela'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cartela',
            field=models.CharField(choices=[('super', 'Super'), ('dallol', 'Dallol'), ('africa', 'Africa'), ('hummer', 'Hummer')], default='dallol', max_length=20),
        ),
    ]
