# Generated by Django 4.2.3 on 2024-07-10 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_account_backup_password_alter_account_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=20)),
                ('total_payed', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('backup_password', models.CharField(default='', max_length=255)),
                ('shop', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='account.account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
