# Generated by Django 4.2.3 on 2024-07-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='total_payed',
        ),
        migrations.AlterField(
            model_name='cashier',
            name='total_collected',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
