# Generated by Django 4.2.3 on 2024-08-01 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_remove_cashier_total_payed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashier',
            name='total_collected',
        ),
    ]
