# Generated by Django 4.2.3 on 2024-08-01 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0003_remove_cashier_total_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='cashier',
            name='last_game_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashier',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
