# Generated by Django 4.2.3 on 2024-05-15 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(default={})),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.CharField(default='20', max_length=50)),
                ('numberofplayers', models.IntegerField(default=0)),
                ('playerCard', models.JSONField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('played', models.CharField(default='Created', max_length=50)),
                ('total_calls', models.IntegerField(default=0)),
                ('winner_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('shop_cut', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('admin_cut', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('winners', models.JSONField(default='[]')),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
