# Generated by Django 4.2.18 on 2025-02-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake', models.CharField(default='20', max_length=50)),
                ('numberofplayers', models.IntegerField(default=0)),
                ('playerCard', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('played', models.CharField(default='STARTED', max_length=50)),
                ('total_calls', models.IntegerField(default=0)),
                ('cut_percentage', models.DecimalField(decimal_places=2, default=0.2, max_digits=5)),
                ('winner_price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('shop_cut', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('admin_cut', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('winners', models.JSONField(default=list)),
                ('free', models.BooleanField(default=False)),
                ('free_hit', models.IntegerField(default=0)),
                ('bonus', models.BooleanField(default=False)),
                ('bonus_payed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashierGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_players', models.JSONField(default=list)),
                ('collected', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('pied', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
