# Generated by Django 4.2.3 on 2024-05-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cut_percentage',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
    ]
