# Generated by Django 4.2.20 on 2025-04-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiergame',
            name='cheacked',
            field=models.BooleanField(default=False),
        ),
    ]
