# Generated by Django 4.2.3 on 2024-05-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game_cut_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='bonus',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='bonus_payed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='played',
            field=models.CharField(default='STARTED', max_length=50),
        ),
    ]
