# Generated by Django 4.2.3 on 2024-03-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='random_numbers',
            field=models.JSONField(default=[0]),
        ),
    ]
