# Generated by Django 4.2.20 on 2025-04-20 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_cashiergame_cheacked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashiergame',
            name='cheacked',
        ),
    ]
