# Generated by Django 4.2.3 on 2024-07-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_cashiergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiergame',
            name='selected_players',
            field=models.JSONField(default='[]'),
        ),
    ]
