# Generated by Django 4.2.3 on 2024-07-18 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_cashiergame_selected_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashiergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game'),
        ),
    ]
