# Generated by Django 4.2.3 on 2024-08-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_game_free_game_free_hit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiergame',
            name='collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AddField(
            model_name='cashiergame',
            name='pied',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
