# Generated by Django 4.2.3 on 2024-12-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_cashiergame_collected_cashiergame_pied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='numbers',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='cashiergame',
            name='selected_players',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='playerCard',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='game',
            name='winners',
            field=models.JSONField(default=list),
        ),
    ]
