# Generated by Django 4.2.3 on 2024-05-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='backup_password',
            field=models.CharField(default='', max_length=255),
        ),
    ]
