# Generated by Django 4.2.3 on 2025-09-26 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_agent_account_user"),
        ("agent", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgentAccount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment_method",
                    models.SmallIntegerField(
                        choices=[
                            (1, "TELEBIRR"),
                            (2, "CBE"),
                            (3, "BOA"),
                            (4, "CBE_BIRR"),
                        ]
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_owner_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="agent.agent",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agent Account",
                "verbose_name_plural": "Agent Accounts",
                "db_table": "agent_accounts",
                "unique_together": {("agent", "payment_method")},
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=38)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "transaction_type",
                    models.SmallIntegerField(
                        blank=True,
                        choices=[(0, "Automatic"), (1, "Manual")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "agent_account",
                    models.ForeignKey(
                        db_column="agent_account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agent.agentaccount",
                    ),
                ),
                (
                    "shop",
                    models.ForeignKey(
                        db_column="account_account_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="account.account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transaction",
            },
        ),
    ]
