# Generated by Django 4.2.3 on 2024-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agent_backup_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cut_bouldery',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='agent',
            name='cut_percentage',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=5),
        ),
    ]
