# Generated by Django 4.2.3 on 2025-09-26 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0002_agentaccount_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="agent_account",
            field=models.ForeignKey(
                db_column="agent_account_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="agent.agentaccount",
            ),
        ),
    ]
