# Generated by Django 4.2.3 on 2024-07-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agent_cut_bouldery_agent_cut_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='cut_bouldery',
        ),
        migrations.RemoveField(
            model_name='agent',
            name='cut_percentage',
        ),
        migrations.AddField(
            model_name='agent',
            name='privilege',
            field=models.BooleanField(default=False),
        ),
    ]
