# Generated by Django 4.2.3 on 2025-09-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agent", "0003_alter_transaction_agent_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.SmallIntegerField(
                blank=True, choices=[(0, "Automatic"), (1, "Manual")], null=True
            ),
        ),
    ]
