# Generated by Django 4.2.3 on 2024-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_remove_agent_cut_bouldery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='min_stake',
            field=models.DecimalField(decimal_places=0, default=20, max_digits=10),
        ),
    ]
