# Generated by Django 4.2.18 on 2025-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
